export const content = {
  en: {
    hero: { name: "Mansur Zhiger", tagline_indie: "Indie dev", tagline_rest: "Almaty. 17." },
    sections: {
      contact: "contact",
      elsewhere: "elsewhere",
      about: "about",
      background: "background",
      experience: "experience",
      wins: "wins",
      field: "field",
      resume: "resume",
    },
    contact: { telegram: "Telegram" },
    about_lines: [
      "Self-taught. From Uralsk, now Almaty.",
      "Build things I actually need. Ship them anyway.",
      "Run mountains when I'm not at the keyboard.",
    ],
    background_lines: [
      "Started coding 1.5 years ago. Taught myself by building things I actually needed.",
      "First project: an Arabic learning app I built because nothing good existed.",
      "First vibe-coded project: CodeVault, a snippet manager. 14 GitHub stars.",
      "Since then: five products solo, $3,000+ from freelance bots, two hackathon placements.",
      "Stack: Next.js, TypeScript, Supabase, Claude Code.",
    ],
    experience_intro: "Five products shipped solo. None at scale yet. Every one started with a problem I actually had.",
    projects: [
      { name: "Restok", desc: "Smart grocery automation. Building now.", detail: "Tracks your fridge, auto-orders through Kaspi when you're running low." },
      { name: "ShipReady", desc: "Security scanner for vibe-coded apps. 80 waitlist signups.", detail: "Next.js, TypeScript, Supabase." },
      { name: "SafeBiz KZ", desc: "Tax compliance SaaS for the 2026 Kazakhstan tax overhaul.", detail: "Next.js, Supabase, Recharts. 120 registrations." },
      { name: "EcoAlmaty", desc: "AI eco-education app. 2nd at EcoSolutions Hackathon 2026.", detail: "Next.js, Tailwind, Anthropic API." },
      { name: "AzamatAI", desc: "Bilingual Russian and Kazakh AI assistant. Built in 24 hours.", detail: "Next.js, Vercel." },
      { name: "CodeVault", desc: "Code snippet manager. PHP and Supabase.", detail: "14 GitHub stars." },
    ],
    wins_lines: [
      "Almaty Marathon. 4:31 at 16.",
      "15 Peaks of Almaty, all three levels in 12 months.",
      "EcoSolutions Hackathon 2026, 2nd place.",
      "\u201cZOZh legko i prosto\u201d health book, ~1,200 copies sold.",
      "$3,000+ from 8+ paying clients in four months.",
    ],
    resume: { pdf: "resume.pdf" },
    closer: "11th grade. Shipping anyway.",

    // Bento layout fields
    hero_intro: "Yo, I am",
    hero_callout: "Couldn't find the right app. Built it myself. Five times now.",
    hero_body: "17. From Uralsk, now Almaty. Got into coding because I wanted to learn Arabic and nothing worked \u2014 so I built my own app. That was 1.5 years ago. Five products since, Telegram bots for 8+ businesses, $3,000+ earned, two hackathon placements. Up at 4am, pray, run, then code from 2pm after school. Right now building Restok \u2014 smart grocery automation that tracks your fridge and auto-orders through Kaspi. Applying for ML and AI Engineering programs.",
    numbers: [
      { value: "1,200+", label: "COPIES OF ZOZh BOOK SOLD" },
      { value: "$3,000+", label: "FROM 8+ PAYING CLIENTS" },
      { value: "80", label: "SHIPREADY WAITLIST SIGNUPS" },
      { value: "120", label: "SAFEBIZ KZ REGISTRATIONS" },
      { value: "4:31", label: "ALMATY MARATHON AT 16" },
      { value: "4400m", label: "HIGHEST ALTITUDE CLIMBED" },
    ],
    recognized_by: [
      "ECOSOLUTIONS HACKATHON 2026, 2ND",
      "SPRING GAMES 2026, 3RD",
      "15 PEAKS OF ALMATY, ALL LEVELS",
    ],
    life_story_paragraphs: [
      "Grew up in Uralsk \u2014 small post-Soviet city in the west of Kazakhstan. Nothing much there. Moved to Almaty at 13. Started coding 1.5 years ago \u2014 not from a course, but because I wanted to learn Arabic and couldn't find an app that actually worked. So I built one. That's still how I pick projects: if I need something and it doesn't exist, I build it.",
      "My first vibe-coded project was CodeVault, a snippet manager that got 14 GitHub stars. After that: SafeBiz KZ for the 2026 Kazakhstan tax overhaul \u2014 120 registrations. EcoAlmaty \u2014 2nd at EcoSolutions Hackathon 2026. AzamatAI \u2014 3rd at Spring Games 2026. Outside products, Telegram bots for 8+ local businesses, $3,000+ in four months.",
      "Daily routine: up at 4am, prayer, run, school, then code until 6pm. Right now building Restok \u2014 it tracks what's in your fridge, figures out what's running low, and auto-orders through Kaspi. You just hit confirm. Also applying for ML and AI Engineering programs internationally.",
    ],
    projects_v2: [
      { index: "01", name: "Restok", status: "building now", description: "Smart grocery automation. Tracks your fridge, auto-orders through Kaspi when you're running low." },
      { index: "02", name: "ShipReady", status: null, description: "Security scanner for vibe-coded apps. 45% of AI-generated apps have vulnerabilities. 80 waitlist signups." },
      { index: "03", name: "EcoAlmaty", status: null, description: "AI eco-education app. 2nd at EcoSolutions Hackathon 2026." },
      { index: "04", name: "SafeBiz KZ", status: null, description: "Tax compliance SaaS for the 2026 Kazakhstan tax overhaul. 120 registrations." },
      { index: "05", name: "AzamatAI", status: null, description: "Bilingual Russian and Kazakh AI assistant. 3rd at Spring Games 2026." },
      { index: "06", name: "CodeVault", status: null, description: "Code snippet manager. PHP and Supabase. 14 GitHub stars." },
    ],
    footer_tagline: "SHIP. RUN. REPEAT.",
    photo_annotations: { builder: "builder", shipper: "shipper", runner: "runner" },
    numbers_label: "Numbers",
    recognized_label: "Recognized by",
    life_story_label: "Life story",
    projects_label: "My projects",
    projects_date: "2024-PRESENT",
    field_label: "Field",
    book_a_call: "Book a call",
  },
  ru: {
    hero: { name: "Мансур Жигер", tagline_indie: "Инди-дев", tagline_rest: "Алматы. 17." },
    sections: {
      contact: "контакты",
      elsewhere: "ещё",
      about: "о себе",
      background: "как дошёл",
      experience: "опыт",
      wins: "победы",
      field: "в полях",
      resume: "резюме",
    },
    contact: { telegram: "Telegram" },
    about_lines: [
      "Самоучка. Из Уральска, теперь в Алматы.",
      "Строю то, чего не хватает. Себе или другим.",
      "Бегаю в горах, когда не за компьютером.",
    ],
    background_lines: [
      "Начал кодить полтора года назад. Учился, строя то, что самому было нужно.",
      "Первый проект — приложение для изучения арабского. Сделал сам, потому что нормального не нашёл.",
      "Первый вайб-кодинг проект: CodeVault, менеджер сниппетов. 14 звёзд на GitHub.",
      "С тех пор: пять продуктов соло, $3 000+ на фрилансе, два места на хакатонах.",
      "Стек: Next.js, TypeScript, Supabase, Claude Code.",
    ],
    experience_intro: "Пять продуктов соло. Масштаба пока нет. Каждый начинался с проблемы, которая у меня реально была.",
    projects: [
      { name: "Restok", desc: "Умная автоматизация продуктовых заказов. Строю сейчас.", detail: "Следит за холодильником, автозаказ через Kaspi." },
      { name: "ShipReady", desc: "Сканер безопасности для вайб-кодинг приложений. 80 в листе ожидания.", detail: "Next.js, TypeScript, Supabase." },
      { name: "SafeBiz KZ", desc: "SaaS по налоговому учёту под реформу Налогового кодекса 2026.", detail: "Next.js, Supabase, Recharts. 120 регистраций." },
      { name: "EcoAlmaty", desc: "ИИ-приложение по экопросвещению. 2-е место на EcoSolutions Hackathon 2026.", detail: "Next.js, Tailwind, Anthropic API." },
      { name: "AzamatAI", desc: "Двуязычный ИИ-ассистент на русском и казахском. Собрал за 24 часа.", detail: "Next.js, Vercel." },
      { name: "CodeVault", desc: "Менеджер сниппетов. PHP и Supabase.", detail: "14 звёзд на GitHub." },
    ],
    wins_lines: [
      "Алматинский марафон. 4:31, в 16 лет.",
      "15 вершин Алматы, все три уровня за 12 месяцев.",
      "EcoSolutions Hackathon 2026, 2-е место.",
      "«ЗОЖ легко и просто» — книга по здоровью, ~1 200 экземпляров.",
      "$3 000+ от 8+ клиентов за четыре месяца.",
    ],
    resume: { pdf: "resume.pdf" },
    closer: "11-й класс. Шиппю несмотря ни на что.",

    // Bento layout fields
    hero_intro: "Я —",
    hero_callout: "Не нашёл нужного приложения — сделал сам. Уже пять раз.",
    hero_body: "17 лет. Из Уральска, теперь в Алматы. Начал кодить потому что хотел учить арабский, а нормального приложения не было — сделал сам. Полтора года назад. С тех пор: пять продуктов, боты для 8+ бизнесов, $3 000+ заработал, два места на хакатонах. Встаю в 4 утра, намаз, пробежка, школа, потом код с 14:00. Сейчас строю Restok — следит за холодильником, понимает что заканчивается, заказывает через Kaspi. Подаю документы на программы ML и AI-инжиниринга.",
    numbers: [
      { value: "1 200+", label: "ЭКЗЕМПЛЯРОВ КНИГИ «ЗОЖ»" },
      { value: "$3 000+", label: "ОТ 8+ КЛИЕНТОВ" },
      { value: "80", label: "SHIPREADY В ЛИСТЕ ОЖИДАНИЯ" },
      { value: "120", label: "РЕГИСТРАЦИЙ SAFEBIZ KZ" },
      { value: "4:31", label: "АЛМАТИНСКИЙ МАРАФОН В 16" },
      { value: "4 400м", label: "МАКСИМАЛЬНАЯ ВЫСОТА" },
    ],
    recognized_by: [
      "ECOSOLUTIONS HACKATHON 2026, 2-Е",
      "SPRING GAMES 2026, 3-Е",
      "15 ВЕРШИН АЛМАТЫ, ВСЕ УРОВНИ",
    ],
    life_story_paragraphs: [
      "Вырос в Уральске — небольшой постсоветский город на западе Казахстана, делать там особо нечего. Переехал в Алматы в 13 лет. Начал кодить полтора года назад — не по курсам, а потому что хотел учить арабский и не нашёл нормального приложения. Сделал сам. Так до сих пор выбираю проекты: если нужного нет — строю.",
      "Первый вайб-кодинг проект — CodeVault, менеджер сниппетов, 14 звёзд на GitHub. Потом: SafeBiz KZ под налоговую реформу 2026 — 120 регистраций. EcoAlmaty — 2-е место на EcoSolutions Hackathon, собрал соло за 8 часов. AzamatAI — 3-е место на Spring Games, двуязычный ассистент на русском и казахском. Параллельно: Telegram-боты для 8+ местных бизнесов, $3 000+ за четыре месяца.",
      "Режим дня: подъём в 4 утра, намаз, пробежка, школа, потом код до 18:00. Сейчас строю Restok — следит что есть в холодильнике, знает когда что-то заканчивается, автоматически заказывает через Kaspi. Ты просто жмёшь подтвердить. Также подаю документы на программы ML и AI-инжиниринга за рубежом.",
    ],
    projects_v2: [
      { index: "01", name: "Restok", status: "сейчас строю", description: "Умная автоматизация продуктовых заказов. Следит за холодильником, автозаказ через Kaspi." },
      { index: "02", name: "ShipReady", status: null, description: "Сканер безопасности для вайб-кодинг приложений. 80 в листе ожидания." },
      { index: "03", name: "EcoAlmaty", status: null, description: "ИИ-приложение по экопросвещению. 2-е место на EcoSolutions Hackathon 2026." },
      { index: "04", name: "SafeBiz KZ", status: null, description: "SaaS по налоговому учёту под реформу Налогового кодекса 2026. 120 регистраций." },
      { index: "05", name: "AzamatAI", status: null, description: "Двуязычный ИИ-ассистент. 3-е место на Spring Games 2026." },
      { index: "06", name: "CodeVault", status: null, description: "Менеджер сниппетов. PHP и Supabase. 14 звёзд." },
    ],
    footer_tagline: "СТРОЙ. БЕГИ. ПОВТОРЯЙ.",
    photo_annotations: { builder: "билдер", shipper: "шиппер", runner: "бегун" },
    numbers_label: "Цифры",
    recognized_label: "Признание",
    life_story_label: "История",
    projects_label: "Мои проекты",
    projects_date: "2024-СЕГОДНЯ",
    field_label: "В полях",
    book_a_call: "Написать",
  },
} as const;

export type Lang = "en" | "ru";
