export const content = {
  en: {
    hero: { name: "Mansur Zhiger", tagline_indie: "Indie dev", tagline_rest: "Almaty. 17." },
    sections: {
      contact: "contact",
      elsewhere: "elsewhere",
      about: "about",
      background: "background",
      experience: "experience",
      wins: "wins",
      field: "field",
      resume: "resume",
    },
    contact: { telegram: "Telegram" },
    about_lines: [
      "Self-taught. From Uralsk, now Almaty.",
      "Build things I actually need. Ship them anyway.",
      "Run mountains when I'm not at the keyboard.",
    ],
    background_lines: [
      "Started coding almost two years ago. Taught myself by building things I actually needed.",
      "First project: an Arabic learning app I built because nothing good existed.",
      "First vibe-coded project: CodeVault, a snippet manager. 14 GitHub stars.",
      "Since then: six products solo, $3,000+ from freelance bots, two hackathon placements.",
      "Now: Rivalscope, a competitive intelligence SaaS. Live at rivalscope.dev with paying customers.",
      "Stack: Next.js, TypeScript, FastAPI, Supabase, Claude Code.",
    ],
    experience_intro: "Six products shipped solo. Rivalscope is live with paying customers. Every one started with a problem I actually had.",
    projects: [
      { name: "Rivalscope", desc: "Competitive intelligence SaaS. Live at $49/mo, launched on Product Hunt.", detail: "Next.js, FastAPI, DeepSeek." },
      { name: "ShipReady", desc: "Security scanner for vibe-coded apps. 80 waitlist signups.", detail: "Next.js, TypeScript, Supabase." },
      { name: "SafeBiz KZ", desc: "Tax compliance SaaS for the 2026 Kazakhstan tax overhaul.", detail: "Next.js, Supabase, Recharts. 120 registrations." },
      { name: "EcoAlmaty", desc: "AI eco-education app. 2nd at EcoSolutions Hackathon 2026.", detail: "Next.js, Tailwind, Anthropic API." },
      { name: "AzamatAI", desc: "Bilingual Russian and Kazakh AI assistant. Built in 24 hours.", detail: "Next.js, Vercel." },
      { name: "CodeVault", desc: "Code snippet manager. PHP and Supabase.", detail: "14 GitHub stars." },
      { name: "Restok", desc: "Smart grocery automation.", detail: "Tracks your fridge, auto-orders through Kaspi when you're running low." },
    ],
    wins_lines: [
      "Rivalscope: first SaaS revenue, $1,280 in 2026.",
      "Almaty Marathon. 4:31 at 16.",
      "15 Peaks of Almaty, all three levels in 12 months.",
      "EcoSolutions Hackathon 2026, 2nd place.",
      "“ZOZh legko i prosto” health book, ~1,200 copies sold.",
      "$3,000+ from 8+ paying clients in four months.",
    ],
    resume: { pdf: "resume.pdf" },
    closer: "11th grade. Shipping anyway.",

    // Bento layout fields
    hero_intro: "Yo, I am",
    hero_callout: "Couldn't find the right app. Built it myself. Six times now.",
    hero_body: "17. From Uralsk, now Almaty. Got into coding because I wanted to learn Arabic and nothing worked, so I built my own app. That was almost two years ago. Six products since, Telegram bots for 8+ businesses, $3,000+ earned, two hackathon placements. Right now all-in on Rivalscope: competitive intelligence that watches your competitors and turns every move into AI battle cards. Live at rivalscope.dev with paying customers, launched on Product Hunt, pitched at nFactorial Demo Day. Up at 4am, pray, run, then code. Applying for ML and AI Engineering programs.",
    numbers: [
      { value: "$1,280", label: "RIVALSCOPE REVENUE IN 2026" },
      { value: "3,000", label: "RIVALSCOPE SIGNUPS" },
      { value: "365", label: "ACTIVE USERS" },
      { value: "$3,000+", label: "FROM 8+ PAYING CLIENTS" },
      { value: "1,200+", label: "COPIES OF HEALTH BOOK SOLD" },
      { value: "4:31", label: "ALMATY MARATHON AT 16" },
    ],
    recognized_by: [
      "PRODUCT HUNT LAUNCH 2026",
      "NFACTORIAL DEMO DAY 2026",
      "ECOSOLUTIONS HACKATHON 2026, 2ND",
      "SPRING GAMES 2026, 3RD",
      "15 PEAKS OF ALMATY, ALL LEVELS",
    ],
    life_story_paragraphs: [
      "Grew up in Uralsk, a small post-Soviet city in the west of Kazakhstan. Nothing much there. Moved to Almaty at 13. Started coding almost two years ago. Not from a course, but because I wanted to learn Arabic and couldn't find an app that actually worked. So I built one. That's still how I pick projects: if I need something and it doesn't exist, I build it.",
      "My first vibe-coded project was CodeVault, a snippet manager that got 14 GitHub stars. After that: SafeBiz KZ for the 2026 Kazakhstan tax overhaul, 120 registrations. EcoAlmaty, 2nd at EcoSolutions Hackathon 2026. AzamatAI, 3rd at Spring Games 2026. Outside products, Telegram bots for 8+ local businesses, $3,000+ in four months.",
      "These days it's all Rivalscope: competitive intelligence for sales teams. It watches your competitors' sites, mines their reviews for complaints, and turns every change into an AI battle card with ready-to-send plays. Live at rivalscope.dev at $49/mo: $1,280 in revenue, 3,000 signups, 365 active users. Launched on Product Hunt and pitched at nFactorial Demo Day 2026. Still up at 4am: prayer, run, then code. And applying for ML and AI Engineering programs internationally.",
    ],
    projects_v2: [
      { index: "01", name: "Rivalscope", status: "live", description: "Competitive intelligence SaaS. AI battle cards on your competitors, updated as they move. $49/mo, launched on Product Hunt.", href: "https://rivalscope.dev" },
      { index: "02", name: "ShipReady", status: null, description: "Security scanner for vibe-coded apps. 45% of AI-generated apps have vulnerabilities. 80 waitlist signups.", href: "https://github.com/IManss-ai/vibescan" },
      { index: "03", name: "EcoAlmaty", status: null, description: "AI eco-education app. 2nd at EcoSolutions Hackathon 2026.", href: "https://github.com/IManss-ai/EcoAlmaty" },
      { index: "04", name: "SafeBiz KZ", status: null, description: "Tax compliance SaaS for the 2026 Kazakhstan tax overhaul. 120 registrations.", href: "https://github.com/IManss-ai/safebiz-kz" },
      { index: "05", name: "AzamatAI", status: null, description: "Bilingual Russian and Kazakh AI assistant. 3rd at Spring Games 2026.", href: null },
      { index: "06", name: "CodeVault", status: null, description: "Code snippet manager. PHP and Supabase. 14 GitHub stars.", href: "https://github.com/IManss-ai/codevault" },
      { index: "07", name: "Restok", status: null, description: "Smart grocery automation. Tracks your fridge, auto-orders through Kaspi when you're running low.", href: null },
    ],
    footer_tagline: "SHIP. RUN. REPEAT.",
    photo_annotations: { builder: "builder", shipper: "shipper", runner: "runner" },
    numbers_label: "Numbers",
    recognized_label: "Recognized by",
    life_story_label: "Life story",
    projects_label: "My projects",
    projects_date: "2024-PRESENT",
    field_label: "Field",
    book_a_call: "Book a call",
  },
  ru: {
    hero: { name: "Мансур Жигер", tagline_indie: "Инди-дев", tagline_rest: "Алматы. 17." },
    sections: {
      contact: "контакты",
      elsewhere: "ещё",
      about: "о себе",
      background: "как дошёл",
      experience: "опыт",
      wins: "победы",
      field: "в полях",
      resume: "резюме",
    },
    contact: { telegram: "Telegram" },
    about_lines: [
      "Самоучка. Из Уральска, теперь в Алматы.",
      "Строю то, чего не хватает. Себе или другим.",
      "Бегаю в горах, когда не за компьютером.",
    ],
    background_lines: [
      "Начал кодить почти два года назад. Учился, строя то, что самому было нужно.",
      "Первый проект: приложение для изучения арабского. Сделал сам, потому что нормального не нашёл.",
      "Первый вайб-кодинг проект: CodeVault, менеджер сниппетов. 14 звёзд на GitHub.",
      "С тех пор: шесть продуктов соло, $3 000+ на фрилансе, два места на хакатонах.",
      "Сейчас: Rivalscope, SaaS конкурентной разведки. Живой продукт на rivalscope.dev с платящими клиентами.",
      "Стек: Next.js, TypeScript, FastAPI, Supabase, Claude Code.",
    ],
    experience_intro: "Шесть продуктов соло. Rivalscope живой, с платящими клиентами. Каждый начинался с проблемы, которая у меня реально была.",
    projects: [
      { name: "Rivalscope", desc: "SaaS конкурентной разведки. Живой продукт за $49/мес, запуск на Product Hunt.", detail: "Next.js, FastAPI, DeepSeek." },
      { name: "ShipReady", desc: "Сканер безопасности для вайб-кодинг приложений. 80 в листе ожидания.", detail: "Next.js, TypeScript, Supabase." },
      { name: "SafeBiz KZ", desc: "SaaS по налоговому учёту под реформу Налогового кодекса 2026.", detail: "Next.js, Supabase, Recharts. 120 регистраций." },
      { name: "EcoAlmaty", desc: "ИИ-приложение по экопросвещению. 2-е место на EcoSolutions Hackathon 2026.", detail: "Next.js, Tailwind, Anthropic API." },
      { name: "AzamatAI", desc: "Двуязычный ИИ-ассистент на русском и казахском. Собрал за 24 часа.", detail: "Next.js, Vercel." },
      { name: "CodeVault", desc: "Менеджер сниппетов. PHP и Supabase.", detail: "14 звёзд на GitHub." },
      { name: "Restok", desc: "Умная автоматизация продуктовых заказов.", detail: "Следит за холодильником, автозаказ через Kaspi." },
    ],
    wins_lines: [
      "Rivalscope: первая SaaS-выручка, $1 280 в 2026.",
      "Алматинский марафон. 4:31, в 16 лет.",
      "15 вершин Алматы, все три уровня за 12 месяцев.",
      "«ЗОЖ легко и просто», книга по здоровью, ~1 200 экземпляров.",
      "$3 000+ от 8+ клиентов за четыре месяца.",
    ],
    resume: { pdf: "resume.pdf" },
    closer: "11-й класс. Шиппю несмотря ни на что.",

    // Bento layout fields
    hero_intro: "Я —",
    hero_callout: "Не нашёл нужного приложения, сделал сам. Уже шесть раз.",
    hero_body: "17 лет. Из Уральска, теперь в Алматы. Начал кодить, потому что хотел учить арабский, а нормального приложения не было. Сделал сам. Это было почти два года назад. С тех пор: шесть продуктов, боты для 8+ бизнесов, $3 000+ заработал, два места на хакатонах. Сейчас полностью в Rivalscope: конкурентная разведка, которая следит за конкурентами и превращает каждый их ход в AI battle card. Живой продукт на rivalscope.dev с платящими клиентами, запуск на Product Hunt, питч на nFactorial Demo Day. Подъём в 4 утра, намаз, пробежка, потом код. Подаю документы на программы ML и AI-инжиниринга.",
    numbers: [
      { value: "$1 280", label: "ВЫРУЧКА RIVALSCOPE В 2026" },
      { value: "3 000", label: "РЕГИСТРАЦИЙ В RIVALSCOPE" },
      { value: "365", label: "АКТИВНЫХ ПОЛЬЗОВАТЕЛЕЙ" },
      { value: "$3 000+", label: "ОТ 8+ КЛИЕНТОВ" },
      { value: "1 200+", label: "ЭКЗЕМПЛЯРОВ КНИГИ О ЗДОРОВЬЕ" },
      { value: "4:31", label: "АЛМАТИНСКИЙ МАРАФОН В 16" },
    ],
    recognized_by: [
      "PRODUCT HUNT, ЗАПУСК 2026",
      "NFACTORIAL DEMO DAY 2026",
      "ECOSOLUTIONS HACKATHON 2026, 2-Е",
      "SPRING GAMES 2026, 3-Е",
      "15 ВЕРШИН АЛМАТЫ, ВСЕ УРОВНИ",
    ],
    life_story_paragraphs: [
      "Вырос в Уральске. Небольшой постсоветский город на западе Казахстана, делать там особо нечего. Переехал в Алматы в 13 лет. Начал кодить почти два года назад. Не по курсам, а потому что хотел учить арабский и не нашёл нормального приложения. Сделал сам. Так до сих пор выбираю проекты: если нужного нет, строю сам.",
      "Первый вайб-кодинг проект: CodeVault, менеджер сниппетов, 14 звёзд на GitHub. Потом: SafeBiz KZ под налоговую реформу 2026, 120 регистраций. EcoAlmaty, 2-е место на EcoSolutions Hackathon, собрал соло за 8 часов. AzamatAI, 3-е место на Spring Games, двуязычный ассистент на русском и казахском. Параллельно: Telegram-боты для 8+ местных бизнесов, $3 000+ за четыре месяца.",
      "Сейчас всё время уходит на Rivalscope: конкурентная разведка для отделов продаж. Следит за сайтами конкурентов, вытаскивает жалобы из их отзывов и превращает каждое изменение в AI battle card с готовыми ходами. Живой продукт на rivalscope.dev за $49/мес: $1 280 выручки, 3 000 регистраций, 365 активных пользователей. Запустился на Product Hunt, питчил на nFactorial Demo Day 2026. Подъём всё так же в 4 утра: намаз, пробежка, потом код. Параллельно подаю документы на программы ML и AI-инжиниринга за рубежом.",
    ],
    projects_v2: [
      { index: "01", name: "Rivalscope", status: "живой продукт", description: "SaaS конкурентной разведки. AI battle cards по конкурентам, обновляются по мере их ходов. $49/мес, запуск на Product Hunt.", href: "https://rivalscope.dev" },
      { index: "02", name: "ShipReady", status: null, description: "Сканер безопасности для вайб-кодинг приложений. 80 в листе ожидания.", href: "https://github.com/IManss-ai/vibescan" },
      { index: "03", name: "EcoAlmaty", status: null, description: "ИИ-приложение по экопросвещению. 2-е место на EcoSolutions Hackathon 2026.", href: "https://github.com/IManss-ai/EcoAlmaty" },
      { index: "04", name: "SafeBiz KZ", status: null, description: "SaaS по налоговому учёту под реформу Налогового кодекса 2026. 120 регистраций.", href: "https://github.com/IManss-ai/safebiz-kz" },
      { index: "05", name: "AzamatAI", status: null, description: "Двуязычный ИИ-ассистент. 3-е место на Spring Games 2026.", href: null },
      { index: "06", name: "CodeVault", status: null, description: "Менеджер сниппетов. PHP и Supabase. 14 звёзд.", href: "https://github.com/IManss-ai/codevault" },
      { index: "07", name: "Restok", status: null, description: "Умная автоматизация продуктовых заказов. Следит за холодильником, автозаказ через Kaspi.", href: null },
    ],
    footer_tagline: "СТРОЙ. БЕГИ. ПОВТОРЯЙ.",
    photo_annotations: { builder: "билдер", shipper: "шиппер", runner: "бегун" },
    numbers_label: "Цифры",
    recognized_label: "Признание",
    life_story_label: "История",
    projects_label: "Мои проекты",
    projects_date: "2024-СЕГОДНЯ",
    field_label: "В полях",
    book_a_call: "Написать",
  },
} as const;

export type Lang = "en" | "ru";
